### ISSUE TITLE
Mac cannot recognize Windows, and Windows cannot recognize Mac either

### ISSUE THREAD

**Issue by qpf521** [CrossPaste/crosspaste-desktop#1723]
### How frequently does the bug occur?

Always

### Description

After updating the new version, Mac cannot recognize Windows, and Windows cannot recognize Mac either. Both IP addresses are displayed normally and are in the state of allowing new device discovery.

### Can you reproduce the bug?

Always

### Version

1.0.7

### OS

macOS 15，Windows10

**Comment by guiyanakuang** [comment]
@qpf521 This sounds problematic. It seems that service discovery is not working in your local area network. Can you use telnet to confirm that these two machines can connect normally?
Perhaps I should add a fallback plan, allowing manual input of IP and port for connection.

**Comment by guiyanakuang** [comment]
Can you execute the following command on Mac?
`dns-sd -B *crosspasteService.*tcp.`

On my Mac, the output is as follows, showing two records, which means there are two crosspaste applications running on the local network. I want to see your results, as this can help determine if it's a service discovery issue or crosspaste recognition issue.
```
Browsing for *crosspasteService.*tcp.
DATE: ---Sat 24 Aug 2024---
17:45:32.022  ...STARTING...
Timestamp     A/R    Flags  if Domain               Service Type         Instance Name
17:45:32.023  Add        3  12 local.               *crosspasteService.*tcp. crosspaste@82539253-135B-5B4A-B458-6A8FF25B40AD@192_168_31_5
17:45:32.023  Add        2  12 local.               *crosspasteService.*tcp. crosspaste@F5F6A504-EE21-11EA-C98C-08BFB81BB86E@192_168_31_204
```

**Comment by qpf521** [comment]
Sorry, I just saw the message. Below is the running result of my Mac computer.
<img width="503" alt="image" src="https://github.com/user-attachments/assets/13685e48-cae7-436b-9a1b-71c698824f55">

**Comment by guiyanakuang** [comment]
I made a mistake 😓. I've corrected the command, replacing * with _:
`dns-sd -B _crosspasteService._tcp.`

**Comment by qpf521** [comment]
I ran this command and the following interface appeared. After waiting for about 1 minute without any changes, I terminated the command.
<img width="505" alt="image" src="https://github.com/user-attachments/assets/afe471a8-b7b3-44df-9984-96f0425dabf1">

**Comment by guiyanakuang** [comment]
Have you already started crosspaste on both Mac and Windows?

**Comment by qpf521** [comment]
Sorry, I forgot to run the application earlier and also turned on VPN. I tried again, and below are the results of the run. Also, for some unknown reason, a huge white window will appear on the Windows side, and it will only disappear after closing Crosspaste.
<img width="1016" alt="image" src="https://github.com/user-attachments/assets/fa214a95-194f-4f03-a5a0-c0d3145f6709">
![image](https://github.com/user-attachments/assets/2042ccb0-2b3d-453b-a074-b13fd6ccc25b)
Moreover, after I input the command, Windows can detect Mac devices, but Mac still cannot detect Windows.

**Comment by qpf521** [comment]
Moreover, after I input the command, Windows can detect Mac devices, but Mac still cannot detect Windows.
At this point, a one-way connection through Windows can be established successfully, and the clipboard transfer function can also be used normally.
Both Mac and Windows display as connected.

**Comment by guiyanakuang** [comment]
It appears that Mac discovered the Windows service, but removed it after twenty seconds (in reality, the broadcast should only close when the Windows process exits). This could be due to several reasons:

1. The local network (router) is unstable
2. Antivirus software or firewall rules are blocking it

I think it would be very difficult to completely solve this problem, as it's closely related to the user's network environment.

Therefore, I've decided to provide a feature in the next version that allows manual input of IP and port for binding. When service discovery is unstable, users can manually bind the connection.

**Comment by qpf521** [comment]
Okay, looking forward to the next version.

**Comment by CompileFuture2024** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
- [ ] #1724
